package wfg.ltv_econ.ui.panels;

import java.awt.Color;

import static wfg.native_ui.util.UIConstants.*;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.econ.CommoditySpecAPI;
import com.fs.starfarer.api.impl.campaign.ids.Factions;
import com.fs.starfarer.api.impl.codex.CodexDataV2;
import com.fs.starfarer.api.ui.Fonts;
import com.fs.starfarer.api.ui.LabelAPI;
import com.fs.starfarer.api.ui.UIPanelAPI;

import wfg.ltv_econ.economy.engine.EconomyEngine;
import wfg.ltv_econ.economy.engine.EconomyInfo;
import wfg.native_ui.ui.components.BackgroundComp;
import wfg.native_ui.ui.components.NativeComponents;
import wfg.native_ui.ui.core.UIElementFlags.HasBackground;
import wfg.native_ui.ui.panels.CustomPanel;
import wfg.native_ui.ui.panels.SortableTable;
import wfg.native_ui.ui.panels.SortableTable.cellAlg;
import wfg.native_ui.ui.panels.SpritePanel.Base;
import wfg.native_ui.util.NumFormat;

public class FactionResourcesTable extends CustomPanel<ColonyPopulationTable> implements HasBackground {
    protected final BackgroundComp bg = comp().get(NativeComponents.BACKGROUND);

    public FactionResourcesTable(UIPanelAPI parent, int height) {
        super(parent, ColonyPopulationTable.PANEL_W, height);

        bg.alpha = 1f;

        createPanel();
    }

    public void createPanel() {
        final EconomyEngine engine = EconomyEngine.getInstance();
        final EconomyInfo info = engine.info;
        final int rowH = 30;
        
        clearChildren();
        final SortableTable table = new SortableTable(m_panel, (int) pos.getWidth(),
            (int) pos.getHeight(), 18, rowH
        );

        table.addHeaders(
            "", 40, null, true, false, 1,
            "Commodity", 160, "All commodities produced or demanded by your faction.", true, true, 1,
            "Stored", 85, "Total stored amount across all faction markets.", false, false, -1,
            "Demand", 95, "Total demand across all faction markets.", false, false, -1,
            "Production", 120, "Total production across all faction markets.", false, false, -1,
            "Mkt Share", 120, "Fraction of global demand covered by your faction's exports.", false, false, -1,
            "Credit Flow", 120, "Credits generated by or spent for this commodity.", false, false, -1,
            "Balance", 100, "Net flow of this commodity for your faction, after production, consumption, and trade.", false, false, -1,
            "Autarky", 95, "Fraction of total demand satisfied using only in-faction production and internal imports. Shows how self-sufficient your faction is for this commodity.", false, false, -1
        );

        if (engine.getPlayerMarketData().size() > 0) {
            for (CommoditySpecAPI com : EconomyInfo.getEconCommodities()) {
                final String comID = com.getId();
                final Base icon = new Base(
                    m_panel, 26, 26, com.getIconName(), null, null
                );
    
                final double stored = info.getTotalFactionStockpiles(comID, Factions.PLAYER);
                final float demand = info.getTotalFactionDemand(comID, Factions.PLAYER);
                final float prod = info.getTotalFactionProd(comID, Factions.PLAYER);
                if (prod == 0f && demand == 0f) continue;
    
                final int exportShare = (int) (info.getFactionTotalExportShare(comID, Factions.PLAYER) * 100);
                final long credits = info.getPlayerFactionCreditFlow(comID);
                final double balance = info.getTotalFactionBalance(comID, Factions.PLAYER);
                final int autarky = (int) (info.getFactionImportSufficiency(comID, Factions.PLAYER) * 100);
    
                final Color demandColor = demand > prod ? negative : base;
                final Color creditsColor = credits < 0 ? negative : highlight;
                final Color balanceColor = balance < 0.0 ? negative : highlight;
    
                table.addCell(icon, cellAlg.MID, null, null);
                table.addCell(com.getName(), cellAlg.LEFT, null, base);
                table.addCell(NumFormat.engNotation(stored), cellAlg.LEFTOPAD, stored, base);
                table.addCell(NumFormat.engNotation(demand), cellAlg.LEFTOPAD, demand, demandColor);
                table.addCell(NumFormat.engNotation(prod), cellAlg.LEFTOPAD, prod, highlight);
                table.addCell(exportShare + "%", cellAlg.LEFTOPAD, exportShare, base);
                table.addCell(NumFormat.formatCredit(credits), cellAlg.LEFTOPAD, credits, creditsColor);
                table.addCell(NumFormat.engNotation(balance), cellAlg.LEFTOPAD, balance, balanceColor);
                table.addCell(autarky + "%", cellAlg.LEFTOPAD, autarky, base);
    
                table.pushRow(
                    null, null, null, CodexDataV2.getCommodityEntryId(com.getId()), null, null
                );
            }
        } else {
            final LabelAPI lbl = Global.getSettings().createLabel("No colonies", Fonts.DEFAULT_SMALL);
            lbl.setColor(base);
            table.add(lbl).inMid();
        }

        table.outline.enabled = true;
        add(table).inTL(0f, 0f);
        table.sortRows(7, false);
    }
}